---
- hosts : all
  gather_facts: false

  tasks:
    - name: Wait for SSH to come up
      wait_for_connection:
        delay: 10
        sleep: 5
        timeout: 300
      vars:
        ansible_user: ec2-user

- hosts: all
  become: true
  vars:
   ansible_user: ec2-user

  tasks:

    - name: Install apache
      yum:
        name: docker
        state: latest
        update_cache: yes

    - name: keep docker enabled
      service:
        name: docker
        enabled: true
        state: started

    - name: Install docker-compose
      pip:
        name: docker-compose
        executable: pip3
    
    - name: ghcr register
      shell: "echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin"

    - name: url docker-compose
      url:
      dest: /home/ec2-user
      owner: ec2-user
      group: ec2-user